# all available settings of specific linters
linters-settings:
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 2
  depguard:
  lll:
    line-length: 160
  nakedret:
    max-func-lines: 10

linters:
  enable:
    - exportloopref
    - megacheck
    - govet
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - gofmt
    - lll
    - revive
    - unparam
    - nakedret
    - misspell
  disable:
    - exhaustive
  enable-all: false
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false
